# -*- coding: utf-8 -*-
"""my_Tespy_StreamIt_case01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3O6WXNwcv4gxAr9ZYqPFHIxzBUSqgy0
"""

#pip install tespy
#pip install fluprodia

#pip install streamlit -q
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
from tespy.networks import Network
from tespy.components import Sink, Source, Turbine, Condenser, Pump, SimpleHeatExchanger
from tespy.connections import Connection
import pandas as pd
import plotly.graph_objects as go
from CoolProp.CoolProp import PropsSI
from fluprodia import FluidPropertyDiagram

nw = Network()
nw.set_attr (T_unit = 'C', p_unit = 'bar', h_unit = 'kJ / kg')

# 1. 페이지 설정
st.set_page_config(page_title="Rankine Cycle T-s Designer", layout="wide")
st.title("♨️ Rankine Cycle & T-s Diagram Visualizer")

# 2. 사이드바 제어판 (Vibe Control)
st.sidebar.header("System Settings")
p_live = st.sidebar.slider("Live Steam Pressure (bar)", 10.0, 150.0, 60.0)
t_live = st.sidebar.slider("Live Steam Temperature (°C)", 300, 600, 480)
p_cond = st.sidebar.slider("Condenser Pressure (bar)", 0.05, 1.0, 0.1)
eta_s_t = st.sidebar.slider("Turbine Isentropic Efficiency", 0.5, 1.0, 0.85)

if st.button("🚀 Run & Update Diagram"):
    # 3. TESPy 네트워크 모델링
    from tespy.components import (
    CycleCloser, Pump, Condenser, Turbine, SimpleHeatExchanger, Source, Sink)
    
    cc = CycleCloser('cycle closer')
    sg = SimpleHeatExchanger('steam generator')
    mc = Condenser('main condenser')
    tu = Turbine('steam turbine')
    fp = Pump('feed pump')
    
    cwso = Source('cooling water source')
    cwsi = Sink('cooling water sink')
    
    from tespy.connections import Connection
    
    c1 = Connection(cc, 'out1', tu, 'in1', label='1')
    c2 = Connection(tu, 'out1', mc, 'in1', label='2')
    c3 = Connection(mc, 'out1', fp, 'in1', label='3')
    c4 = Connection(fp, 'out1', sg, 'in1', label='4')
    c0 = Connection(sg, 'out1', cc, 'in1', label='0')
    
    nw.add_conns(c1, c2, c3, c4, c0)
    
    c11 = Connection(cwso, 'out1', mc, 'in2', label='11')
    c12 = Connection(mc, 'out2', cwsi, 'in1', label='12')
    
    nw.add_conns(c11, c12)
    
    # 파라미터 적용
    mc.set_attr(pr1=1, pr2=0.98)
    sg.set_attr(pr=0.9)
    tu.set_attr(eta_s=0.9)
    fp.set_attr(eta_s=0.75)
    
    c11.set_attr(T=20, p=1.2, fluid={'water': 1})
    c12.set_attr(T=30)
    c1.set_attr(T=t_live, p=p_live, m=10, fluid={'water': 1})
    c2.set_attr(p=p_cond)

    try:
        nw.solve(mode='design')
        # --- fluprodia를 이용한 T-s 선도 생성 파트 ---
        diagram = FluidPropertyDiagram('water')
        diagram.set_unit_system(T='°C', p='bar', h='kJ/kg')
        isolines = {
            'Q': np.linspace(0, 1, 11), # 등건도선 추가
            'p': np.array([1, 5, 10, 50, 100, 150]),
            'h': np.arange(500, 4001, 500)
        }
        # 결과 데이터 추출
        res = nw.results['Connection']
        # T-s 선도를 위한 데이터 정렬 (1->2->3->4->1 순서)
        points = ['1', '2', '3', '4', '1']
        t_data = [res.loc[p, 'T'] for p in points]
        s_data = [res.loc[p, 's'] for p in points]

        # 4. 레이아웃 배치
        col_metrics, col_chart = st.columns([1, 2])

        with col_metrics:
            st.subheader("Performance Metrics")
            net_power = (tu.P.val + fp.P.val) / 1e6
            efficiency = abs(net_power / (sg.Q.val / 1e6)) * 100
            st.metric("Thermal Efficiency", f"{efficiency:.2f} %")
            st.metric("Net Power Output", f"{net_power:.2f} MW")
            st.write("---")
            st.dataframe(res[['p', 'T', 's', 'x']])

        with col_chart:
            st.subheader("T-s Diagram")
            fig = go.Figure()
            
            # 등고선 추가
            result_dict={}
            for key, data in result_dict.items():
                result_dict[key]['datapoints'] = diagram.calc_individual_isoline(**data)

            diagram.set_isolines(**isolines)
            diagram.calc_isolines()
        
            # T-s 배경 그리기 (x_max는 J/kgK 단위이므로 주의)
            diagram.draw_isolines(fig, ax, 'Ts', x_min=0, x_max=9000, y_min=0, y_max=650)


            
            # 사이클 라인 추가
            fig.add_trace(go.Scatter(
                x=s_data, y=t_data,
                mode='lines+markers+text',
                text=points,
                textposition="top center",
                line=dict(color='firebrick', width=3),
                name='Rankine Cycle'
            ))

            fig.update_layout(
                xaxis_title="Entropy (kJ/kgK)",
                yaxis_title="Temperature (°C)",
                template="plotly_white",
                height=500
            )
            st.plotly_chart(fig, use_container_width=True)

    except Exception as e:
        st.error(f"계산 에러가 발생했습니다: {e}")

# 3
#import urllib
#print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

# "Password/Enpoint IP for localtunnel is:" 우측에 xx.xxx.xx.xxx 혹은 xx.xxx.xxx.xxx 형식의 숫자가 나온다.

#!npm install localtunnel

#!npm audit fix --force

# 1. 터널링을 통해 URL 생성 (나오는 IP 주소를 복사)
# !streamlit run app.py & npx localtunnel --port 8501
